### ISSUE TITLE
Please consider using a namespace

### ISSUE THREAD

**Issue by szepeviktor** [chandrapatel/wp-custom-settings#2]
e.g.

```php
namespace ChandraPatel\WordPress\CustomSettings;

class Plugin ...

class Section ...

class Field ...
```

**Comment by chandrapatel** [comment]
Hi @szepeviktor 

Thanks for opening an issue and pull request #1.

> Hello! Actually this is a small step in the wrong direction.
> If you examine WP core and WC, Automattic moves in the OOP direction:
> Please consider using a namespace

I haven't initially considered these points because `WP Custom Settings` is a small library and a simple way to reduce the development using Settings API.

I'd suggest using it by adding the main file directly either in theme or plugin to avoid external dependency and developer can modify it as per their need.

So keeping it in a single file would be better instead of adding an entire folder with multiple files. That was my thinking when I started work on this.

Please let me know your thoughts on this. Feedback and suggestions will be appreciated :)

Thanks,

**Comment by szepeviktor** [comment]
Okay-okay.

I think your decision is heavily influenced by your users.

1. "Let's download a single file!" guy 💪 
1. "I always use Composer" guy 🧠

**Comment by chandrapatel** [comment]
@szepeviktor I'll add the namespace and keep the single file. So it can be added using the composer. So I'm reopening this issue.

Thanks,

**Comment by chandrapatel** [comment]
I have added namespace and also added composer package. https://packagist.org/packages/chandrapatel/wp-custom-settings

So closing this issue.

**Comment by szepeviktor** [comment]
Okay-okay :)
I do not nag your further `class WP_Custom_Settings_Field` -> `class Field`
